import { ComparisonData } from "@/types/gallery";

export const GALLERY_COMPARISONS: ComparisonData[] = [
  {
    id: "comp-01",
    stageNumber: 1,
    title: "RAW SAR → AI SEGMENTATION",
    subtitle: "Sentinel-1 C-Band synthetic aperture radar transformation into continuous deep-learning oil slick segmentation.",
    category: "Detection",
    confidence: 94.2,
    timestampUtc: "2026-09-12 04:12:08 UTC",
    satelliteSensor: "Sentinel-1A IW GRD",
    resolution: "10m Spatial",
    areaKm2: 14.2,
    gpuProcessingMs: 42,
    beforeLabel: "Raw Sentinel-1 IW GRD",
    afterLabel: "AI Segmentation Mask & Heatmap",
    beforeDescription: "Raw C-Band SAR radar backscatter containing speckle noise, dark ocean backscatter, bright land reflections, and ship signatures.",
    afterDescription: "Amber contamination polygon overlay, confidence probability heatmap gradient (15% to 94.2%), and contour probability bounds.",
    renderType: "sar_seg",
    whatChanged: "The noisy grayscale SAR backscatter raster was transformed into a classified vector oil spill polygon with confidence probability shading.",
    whyItChanged: "Mineral oil dampens short capillary ocean surface waves (wavelength ~2-5cm), causing a sharp drop in C-band radar backscatter (dark anomaly).",
    aiReasoning: "SegFormer-B5 multi-scale neural net identified a contiguous low-backscatter region with -8.4 dB drop relative to surrounding seawater background.",
    scientificInterpretation: "Bragg scattering suppression: capillary wave height reduced by oil surface tension, lowering normalized radar cross-section (NRCS sigma-0).",
    judgeTakeaway: "Proves SAGAR-DRISHTI isolates genuine oil spills from raw satellite imagery automatically in 42 milliseconds with 94.2% neural certainty.",
    metrics: [
      { label: "Spill Area", value: "14.20", unit: "km²", trend: "up" },
      { label: "AI Confidence", value: "94.2", unit: "%", trend: "up" },
      { label: "Backscatter Drop", value: "-8.4", unit: "dB", trend: "down" },
      { label: "GPU Latency", value: "42", unit: "ms", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a1-1",
        type: "callout",
        x: 48,
        y: 42,
        label: "Primary Slick Core",
        detail: "Confidence 94.2% · Sig0 = -24.8 dB",
        color: "amber",
      },
      {
        id: "a1-2",
        type: "arrow",
        x: 72,
        y: 28,
        label: "Low-Backscatter Boundary",
        detail: "Capillary wave damping zone",
        color: "aqua",
      },
      {
        id: "a1-3",
        type: "box",
        x: 35,
        y: 65,
        label: "Vessel Discharge Origin",
        detail: "Ship blip with trailing wake",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -24.8,
      vhDb: -31.2,
      textureEntropy: 0.12,
      confidence: 94.2,
      classification: "Heavy Mineral Oil",
      backscatterSigma0: 0.0033,
    },
  },
  {
    id: "comp-02",
    stageNumber: 2,
    title: "SPECKLE FILTERING",
    subtitle: "Adaptive Enhanced Lee 7x7 spatial filter removing multiplicative Rayleigh noise while preserving edge boundaries.",
    category: "Preprocessing",
    confidence: 98.1,
    timestampUtc: "2026-09-12 04:12:15 UTC",
    satelliteSensor: "Sentinel-1A IW GRD",
    resolution: "10m Spatial",
    areaKm2: 14.2,
    gpuProcessingMs: 18,
    beforeLabel: "Raw Granular SAR",
    afterLabel: "Enhanced Lee Filtered",
    beforeDescription: "Coherent radar interference creates multiplicative Rayleigh speckle noise across the ocean surface, degrading boundary detection.",
    afterDescription: "Denoised ocean backscatter matrix preserving sharp oil-water boundary gradients and small vessel scatterers.",
    renderType: "speckle",
    whatChanged: "Granular noise artifacts were suppressed while slick boundaries and high-intensity vessel blips remained razor sharp.",
    whyItChanged: "Enhanced Lee filtering computes local variance inside a 7x7 pixel window, selectively smoothing homogeneous sea areas while preserving sharp edges.",
    aiReasoning: "Local variance matrix damping isolates random phase interference without blurring the critical 0.12 entropy transition line.",
    scientificInterpretation: "Signal-to-Noise Ratio (SNR) improved by +14.2 dB; texture entropy reduced by 64.8%, boosting downstream segmentation precision.",
    judgeTakeaway: "Filtering eliminates false alarms caused by sea clutter, ensuring only real hydrodynamic anomalies enter the AI pipeline.",
    metrics: [
      { label: "SNR Improvement", value: "+14.2", unit: "dB", trend: "up" },
      { label: "Entropy Reduction", value: "64.8", unit: "%", trend: "down" },
      { label: "Edge Preservation", value: "0.98", unit: "index", trend: "up" },
      { label: "Kernel Window", value: "7x7", unit: "px", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a2-1",
        type: "callout",
        x: 30,
        y: 40,
        label: "Preserved Slick Boundary",
        detail: "Edge gradient > 0.95 maintained",
        color: "teal",
      },
      {
        id: "a2-2",
        type: "arrow",
        x: 65,
        y: 60,
        label: "Filtered Rayleigh Noise",
        detail: "Local variance smoothed",
        color: "aqua",
      },
    ],
    basePixel: {
      lat: "18.9220° N",
      lon: "72.8350° E",
      vvDb: -16.4,
      vhDb: -26.1,
      textureEntropy: 0.08,
      confidence: 98.1,
      classification: "Filtered Ocean Surface",
      backscatterSigma0: 0.0229,
    },
  },
  {
    id: "comp-03",
    stageNumber: 3,
    title: "VV VS VH POLARIZATION",
    subtitle: "Dual-polarimetric radar analysis isolating surface capillary damping from hard metallic target cross-scattering.",
    category: "Polarimetry",
    confidence: 96.5,
    timestampUtc: "2026-09-12 04:12:22 UTC",
    satelliteSensor: "Sentinel-1 Dual-Pol (VV+VH)",
    resolution: "10m Spatial",
    areaKm2: 14.2,
    gpuProcessingMs: 29,
    beforeLabel: "VV Co-Polarization (Vertical)",
    afterLabel: "VH Cross-Pol & VV/VH Ratio Anomaly",
    beforeDescription: "Co-polarized VV return measures sea surface roughness; oil slicks appear as dark patches due to wave damping.",
    afterDescription: "Cross-polarized VH return isolates metallic vessel hulls while VV/VH ratio clearly discriminates oil from natural look-alikes.",
    renderType: "polarization",
    whatChanged: "Comparison reveals how VV isolates water surface damping while VH isolates metallic ship hulls, removing look-alike ambiguity.",
    whyItChanged: "Water surfaces produce zero cross-polarimetric rotation, making oil invisible in VH, whereas ship structures depolarize radar signals intensely.",
    aiReasoning: "Dual-polarimetric ratio VV/VH drops below -12 dB over oil, while ship targets exceed +18 dB, creating binary discrimination.",
    scientificInterpretation: "Polarimetric decomposition separates surface scattering (Bragg) from volume & double-bounce scattering (vessel hulls).",
    judgeTakeaway: "Eliminates false positives like algae blooms or low-wind calm sea zones, guaranteeing legally sound slick classification.",
    metrics: [
      { label: "VV/VH Slick Ratio", value: "-12.4", unit: "dB", trend: "down" },
      { label: "Vessel VH Bounce", value: "+21.8", unit: "dB", trend: "up" },
      { label: "Look-Alike Rejection", value: "99.4", unit: "%", trend: "up" },
      { label: "Swath Polarization", value: "VV+VH", unit: "Dual", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a3-1",
        type: "callout",
        x: 52,
        y: 45,
        label: "Oil Slick (VV Damped, VH Dark)",
        detail: "Ratio = -12.4 dB",
        color: "amber",
      },
      {
        id: "a3-2",
        type: "arrow",
        x: 28,
        y: 70,
        label: "Metallic Hull (Strong VH Return)",
        detail: "Ratio = +21.8 dB",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.9205° N",
      lon: "72.8335° E",
      vvDb: -22.1,
      vhDb: -34.5,
      textureEntropy: 0.15,
      confidence: 96.5,
      classification: "Mineral Oil (Dual-Pol Verified)",
      backscatterSigma0: 0.0062,
    },
  },
  {
    id: "comp-04",
    stageNumber: 4,
    title: "SATELLITE RGB VS SAR",
    subtitle: "Demonstrating SAR's cloud-penetrating 24/7 all-weather advantage over optical satellite sensors.",
    category: "Multi-Sensor",
    confidence: 99.0,
    timestampUtc: "2026-09-12 04:12:30 UTC",
    satelliteSensor: "Sentinel-2 MSI vs Sentinel-1 SAR",
    resolution: "10m Multi-Spectral",
    areaKm2: 14.2,
    gpuProcessingMs: 15,
    beforeLabel: "Optical RGB (Sentinel-2)",
    afterLabel: "Active C-Band SAR (Sentinel-1)",
    beforeDescription: "Sentinel-2 optical RGB image completely blocked by 92% monsoon cloud cover and heavy maritime humidity/night gloom.",
    afterDescription: "Sentinel-1 active microwave radar passes through clouds, mist, and night darkness, mapping the slick perfectly.",
    renderType: "rgb_sar",
    whatChanged: "Cloud-covered invisible sea view was replaced by high-contrast microwave radar imagery penetrating all weather.",
    whyItChanged: "C-band microwave radar (wavelength 5.55 cm) passes unimpeded through atmospheric water droplets, fog, and cloud layers.",
    aiReasoning: "Multi-sensor fusion pipeline defaults to SAR during cloud cover > 20%, ensuring continuous operational uptime.",
    scientificInterpretation: "Active radar emits its own electromagnetic energy, eliminating reliance on solar illumination for 24/7 night capability.",
    judgeTakeaway: "SAGAR-DRISHTI guarantees zero surveillance blackout during heavy Indian monsoons or midnight oil dumping.",
    metrics: [
      { label: "Cloud Penetration", value: "100.0", unit: "%", trend: "up" },
      { label: "Night Capability", value: "24/7", unit: "Active", trend: "up" },
      { label: "Radar Frequency", value: "5.405", unit: "GHz", trend: "neutral" },
      { label: "Optical Cloud Block", value: "92.4", unit: "%", trend: "down" },
    ],
    annotations: [
      {
        id: "a4-1",
        type: "callout",
        x: 40,
        y: 35,
        label: "92% Cloud Coverage (Optical Block)",
        detail: "Sentinel-2 RGB unusable",
        color: "red",
      },
      {
        id: "a4-2",
        type: "arrow",
        x: 60,
        y: 55,
        label: "C-Band Radar Penetration",
        detail: "Slick mapped with 10m precision",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.9218° N",
      lon: "72.8345° E",
      vvDb: -23.5,
      vhDb: -30.8,
      textureEntropy: 0.11,
      confidence: 99.0,
      classification: "SAR Clear Radar Return",
      backscatterSigma0: 0.0045,
    },
  },
  {
    id: "comp-05",
    stageNumber: 5,
    title: "OIL SHEEN DETECTION",
    subtitle: "Spectral thickness discrimination isolating ultra-thin rainbow sheens from heavy unrefined crude slicks.",
    category: "Classification",
    confidence: 91.8,
    timestampUtc: "2026-09-12 04:13:05 UTC",
    satelliteSensor: "Sentinel-1 + RISAT-1A Multi-Angle",
    resolution: "10m Spatial",
    areaKm2: 14.2,
    gpuProcessingMs: 38,
    beforeLabel: "Baseline Water Backscatter",
    afterLabel: "Sheen Thickness Classification Map",
    beforeDescription: "Uniform water surface backscatter without spectral thickness breakdown.",
    afterDescription: "Multi-layered thickness map: Silver sheen (0.05μm), Rainbow sheen (0.3-5.0μm), and Heavy slick core (>50μm).",
    renderType: "sheen",
    whatChanged: "Uniform slick polygon classified into precise optical/radar film thickness layers.",
    whyItChanged: "Interference colors and backscatter damping intensity vary proportionally with oil film thickness on seawater.",
    aiReasoning: "Random Forest spectral estimator calculates thickness distribution from multi-angle backscatter attenuation coefficient.",
    scientificInterpretation: "Film thickness ranges from 0.15 μm at thin trailing fringes up to 52.0 μm at the dense discharge epicenter.",
    judgeTakeaway: "Allows Coast Guard to estimate total spill volume (142 m³) and assess environmental severity accurately.",
    metrics: [
      { label: "Max Thickness", value: "52.0", unit: "μm", trend: "up" },
      { label: "Est. Total Volume", value: "142.0", unit: "m³", trend: "up" },
      { label: "Rainbow Sheen Area", value: "4.8", unit: "km²", trend: "neutral" },
      { label: "Heavy Core Area", value: "9.4", unit: "km²", trend: "up" },
    ],
    annotations: [
      {
        id: "a5-1",
        type: "callout",
        x: 55,
        y: 45,
        label: "Heavy Crude Slick (>50 μm)",
        detail: "High environmental risk zone",
        color: "amber",
      },
      {
        id: "a5-2",
        type: "arrow",
        x: 75,
        y: 30,
        label: "Rainbow Sheen Fringe (0.3-5.0 μm)",
        detail: "Interference dispersion zone",
        color: "aqua",
      },
    ],
    basePixel: {
      lat: "18.9210° N",
      lon: "72.8340° E",
      vvDb: -25.2,
      vhDb: -32.1,
      textureEntropy: 0.18,
      confidence: 91.8,
      classification: "Heavy Crude (52 μm)",
      backscatterSigma0: 0.0030,
    },
  },
  {
    id: "comp-06",
    stageNumber: 6,
    title: "CONTAMINATION HEATMAP",
    subtitle: "Continuous spatial density estimation mapping volumetric hydrocarbon concentration across coastal waters.",
    category: "Risk Heatmap",
    confidence: 93.7,
    timestampUtc: "2026-09-12 04:14:10 UTC",
    satelliteSensor: "SAR + INCOIS Coastal Mesh",
    resolution: "10m Grid",
    areaKm2: 14.2,
    gpuProcessingMs: 24,
    beforeLabel: "Binary Boundary Detection",
    afterLabel: "Hydrocarbon Volumetric Heatmap",
    beforeDescription: "Simple binary boundary outlining the perimeter of the oil contamination zone.",
    afterDescription: "Continuous color gradient heatmap highlighting critical high-density accumulation zones in crimson & gold.",
    renderType: "heatmap",
    whatChanged: "Binary polygon replaced by a continuous density gradient representing volumetric hydrocarbon mass distribution.",
    whyItChanged: "Hydrocarbon mass is non-uniformly distributed; convergence currents concentrate 78% of oil mass into 22% of total spill area.",
    aiReasoning: "Kernel Density Estimation (KDE) with adaptive Gaussian bandwidth identifies core accumulation hotspot.",
    scientificInterpretation: "Peak mass density reaches 18.4 metric tons/km² at the central convergence locus.",
    judgeTakeaway: "Directs Coast Guard response ships to deploy oil skimmers exactly where contamination is highest.",
    metrics: [
      { label: "Peak Hydrocarbon Density", value: "18.4", unit: "t/km²", trend: "up" },
      { label: "Core Hotspot Area", value: "3.1", unit: "km²", trend: "neutral" },
      { label: "Total Mass", value: "128.5", unit: "tonnes", trend: "up" },
      { label: "KDE Bandwidth", value: "250", unit: "m", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a6-1",
        type: "callout",
        x: 50,
        y: 48,
        label: "Volumetric Peak (18.4 t/km²)",
        detail: "Immediate skimming priority",
        color: "red",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -26.1,
      vhDb: -33.4,
      textureEntropy: 0.22,
      confidence: 93.7,
      classification: "Critical Density Locus",
      backscatterSigma0: 0.0025,
    },
  },
  {
    id: "comp-07",
    stageNumber: 7,
    title: "STATIC SPILL → RK4 ORIGIN",
    subtitle: "Lagrangian 4th-Order Runge-Kutta particle back-trajectory reconstructing spill origin location in reverse time.",
    category: "Physics",
    confidence: 95.4,
    timestampUtc: "2026-09-12 04:15:00 UTC",
    satelliteSensor: "INCOIS + ECMWF Hydrodynamics",
    resolution: "Lagrangian Particles",
    areaKm2: 14.2,
    gpuProcessingMs: 64,
    beforeLabel: "Observed Slick Position (T = 0)",
    afterLabel: "RK4 Reverse Drift Path (T = -12h)",
    beforeDescription: "Static observation of oil slick position at satellite overpass time T = 0.",
    afterDescription: "Animated particle trajectory stepping backward in time to converge on exact discharge origin coordinates.",
    renderType: "rk4",
    whatChanged: "Static slick footprint transformed into a 12-hour reverse hydrodynamic trajectory pinpointing release location.",
    whyItChanged: "Oil particles drift under combined action of surface currents, windage, and wave Stokes drift back to origin.",
    aiReasoning: "RK4 integration computes particle movement backwards with Δt = 300s using bilinear velocity interpolation.",
    scientificInterpretation: "Particles backward-converge into a tight 180m uncertainty ellipse at T = -12.4 hours.",
    judgeTakeaway: "Establishes the exact geographical coordinates and time window where illegal dumping occurred.",
    metrics: [
      { label: "Origin Convergence Radius", value: "180", unit: "m", trend: "down" },
      { label: "Backtrack Duration", value: "12.4", unit: "hrs", trend: "up" },
      { label: "Particle Array", value: "2,500", unit: "count", trend: "neutral" },
      { label: "RK4 Integrator Step", value: "300", unit: "sec", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a7-1",
        type: "callout",
        x: 32,
        y: 68,
        label: "Reconstructed Release Point (T = -12.4h)",
        detail: "18.8942° N, 72.7915° E",
        color: "teal",
      },
      {
        id: "a7-2",
        type: "arrow",
        x: 62,
        y: 38,
        label: "Observed Slick Position (T = 0h)",
        detail: "Satellite overpass location",
        color: "amber",
      },
    ],
    basePixel: {
      lat: "18.8942° N",
      lon: "72.7915° E",
      vvDb: -18.2,
      vhDb: -27.4,
      textureEntropy: 0.06,
      confidence: 95.4,
      classification: "Spill Release Epicenter",
      backscatterSigma0: 0.0151,
    },
  },
  {
    id: "comp-08",
    stageNumber: 8,
    title: "WITHOUT CURRENTS VS WITH CURRENTS",
    subtitle: "Comparing naive linear reverse extrapolation against INCOIS high-resolution coastal current dynamics.",
    category: "Physics",
    confidence: 97.2,
    timestampUtc: "2026-09-12 04:15:30 UTC",
    satelliteSensor: "INCOIS High-Res Coastal Model",
    resolution: "500m Current Mesh",
    areaKm2: 14.2,
    gpuProcessingMs: 22,
    beforeLabel: "Naive Linear Extrapolation (No Currents)",
    afterLabel: "INCOIS Hydrodynamic Vector Mesh",
    beforeDescription: "Straight line backtrack assuming static water, leading to severe positional drift errors.",
    afterDescription: "Curved drift trajectory incorporating INCOIS 1.8 knot surface ocean velocity vectors.",
    renderType: "currents",
    whatChanged: "Straight erroneous backtrack path replaced by curved hydrodynamic trajectory driven by real-time ocean currents.",
    whyItChanged: "Coastal ocean currents off Mumbai flow non-linearly due to tidal forces and bathymetry, inducing 14.8 nmi drift offset.",
    aiReasoning: "INCOIS hydrodynamic mesh integration reduces origin error from 14.8 nmi down to less than 0.18 nmi.",
    scientificInterpretation: "Surface current velocity magnitude 0.92 m/s at 240° heading shifts particle centroid dynamically.",
    judgeTakeaway: "Proves mathematical rigor; naive models fail in court, while SAGAR-DRISHTI uses real ocean physics.",
    metrics: [
      { label: "Current Drift Offset", value: "14.8", unit: "nmi", trend: "up" },
      { label: "INCOIS Velocity", value: "0.92", unit: "m/s", trend: "neutral" },
      { label: "Origin Error Reduction", value: "98.8", unit: "%", trend: "up" },
      { label: "Mesh Grid Res", value: "500", unit: "m", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a8-1",
        type: "callout",
        x: 75,
        y: 25,
        label: "Naive Model Error (14.8 nmi Off)",
        detail: "Ignores INCOIS tidal current",
        color: "red",
      },
      {
        id: "a8-2",
        type: "arrow",
        x: 35,
        y: 65,
        label: "True Hydrodynamic Origin",
        detail: "INCOIS vector validated",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.8940° N",
      lon: "72.7912° E",
      vvDb: -19.1,
      vhDb: -28.0,
      textureEntropy: 0.05,
      confidence: 97.2,
      classification: "INCOIS Current Vector Point",
      backscatterSigma0: 0.0123,
    },
  },
  {
    id: "comp-09",
    stageNumber: 9,
    title: "WITHOUT WIND VS WITH WIND",
    subtitle: "Atmospheric ECMWF 10m wind stress vector integration including 3.2% leeway factor and Ekman spiral offset.",
    category: "Physics",
    confidence: 96.1,
    timestampUtc: "2026-09-12 04:16:00 UTC",
    satelliteSensor: "ECMWF HRES 10m Wind Fields",
    resolution: "0.1° Atmospheric Grid",
    areaKm2: 14.2,
    gpuProcessingMs: 19,
    beforeLabel: "Current-Only Drift Path",
    afterLabel: "ECMWF Windage & Ekman Spiral Added",
    beforeDescription: "Drift model considering ocean currents only, omitting atmospheric wind stress forces on oil film.",
    afterDescription: "Combined hydrodynamic drift trajectory with 3.2% windage factor and 15° Coriolis Ekman deflection.",
    renderType: "wind",
    whatChanged: "Wind vectors added to current vectors, shifting predicted origin point 3.2 nmi northeastward.",
    whyItChanged: "Wind directly pushes surface oil film at approximately 3.2% of 10m wind speed with Coriolis Ekman deflection.",
    aiReasoning: "ECMWF 14 knot southwest wind field applies 0.23 m/s windage vector to particle advection matrix.",
    scientificInterpretation: "Ekman spiral dynamics rotate wind-driven surface layer 15° right of wind direction in Northern Hemisphere.",
    judgeTakeaway: "Provides complete 3D environmental modeling combining ocean hydrodynamics and atmospheric forces.",
    metrics: [
      { label: "10m Wind Speed", value: "14.2", unit: "kts", trend: "neutral" },
      { label: "Leeway Factor", value: "3.2", unit: "%", trend: "neutral" },
      { label: "Ekman Deflection", value: "15.0", unit: "deg", trend: "neutral" },
      { label: "Wind Offset Shift", value: "3.2", unit: "nmi", trend: "up" },
    ],
    annotations: [
      {
        id: "a9-1",
        type: "callout",
        x: 45,
        y: 40,
        label: "ECMWF 10m Wind Vector (225° SW)",
        detail: "14.2 kts surface wind stress",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.8945° N",
      lon: "72.7920° E",
      vvDb: -18.8,
      vhDb: -27.8,
      textureEntropy: 0.07,
      confidence: 96.1,
      classification: "Windage Corrected Locus",
      backscatterSigma0: 0.0131,
    },
  },
  {
    id: "comp-10",
    stageNumber: 10,
    title: "AIS CLUTTER → AI SUSPECT RANKING",
    subtitle: "Spatiotemporal correlation engine filtering 30 candidate vessels down to top suspects using Bayesian scoring.",
    category: "AIS",
    confidence: 94.8,
    timestampUtc: "2026-09-12 04:17:20 UTC",
    satelliteSensor: "Space-Based AIS + Coastal Radar",
    resolution: "Real-time Telemetry",
    areaKm2: 14.2,
    gpuProcessingMs: 52,
    beforeLabel: "Raw AIS Corridor Clutter (30 Vessels)",
    afterLabel: "AI Suspect Ranking & Pulse Highlight",
    beforeDescription: "Dense shipping lane traffic containing 30 vessels passing through Mumbai offshore EEZ.",
    afterDescription: "Ranked attribution list highlighting Primary Suspect #1 (MV OCEAN CROWN - 94.8% probability) with target pulse.",
    renderType: "ais_ranking",
    whatChanged: "Crowded clutter map filtered into a clear, prioritized list of candidate vessels with suspect scores.",
    whyItChanged: "Spatiotemporal distance matrix cross-references vessel trajectory histories against RK4 spill origin hotspot.",
    aiReasoning: "Bayesian Attribution Engine evaluates backtrack proximity, heading alignment, speed anomaly, and AIS continuity.",
    scientificInterpretation: "MV OCEAN CROWN passed within 140m of RK4 origin at exact timestamp T = -12.4h with 94.8% posterior probability.",
    judgeTakeaway: "Instantly identifies the culprit vessel without manual radar log inspection.",
    metrics: [
      { label: "Primary Suspect Score", value: "94.8", unit: "%", trend: "up" },
      { label: "Target Vessel", value: "MV OCEAN CROWN", subtext: "IMO 9123456" },
      { label: "Distance to Origin", value: "140", unit: "m", trend: "down" },
      { label: "Candidates Evaluated", value: "30", unit: "vessels", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a10-1",
        type: "callout",
        x: 42,
        y: 48,
        label: "RANK #1: MV OCEAN CROWN (94.8%)",
        detail: "IMO 9123456 · Tanker · Panama Flag",
        color: "amber",
      },
      {
        id: "a10-2",
        type: "arrow",
        x: 70,
        y: 25,
        label: "Cleared Commercial Traffic",
        detail: "Scores < 12.0%",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.8942° N",
      lon: "72.7915° E",
      vvDb: -12.0,
      vhDb: -18.4,
      textureEntropy: 0.42,
      confidence: 94.8,
      classification: "Culprit Vessel Target (IMO 9123456)",
      backscatterSigma0: 0.0631,
    },
  },
  {
    id: "comp-11",
    stageNumber: 11,
    title: "NORMAL ROUTE VS BLACKOUT ROUTE",
    subtitle: "Dead-reckoning kinematically reconstructing dark vessel path during 4.2-hour AIS transponder gap.",
    category: "AIS",
    confidence: 98.9,
    timestampUtc: "2026-09-12 04:18:05 UTC",
    satelliteSensor: "Satellite AIS + Kalman Interpolation",
    resolution: "Kinematic Track",
    areaKm2: 14.2,
    gpuProcessingMs: 31,
    beforeLabel: "Gapped AIS Track (4.2h Gap)",
    afterLabel: "Reconstructed Dark Path & Origin Match",
    beforeDescription: "Discontinuous AIS broadcast track showing a 4.2-hour silent window where vessel disabled transponder.",
    afterDescription: "Kalman Filter dead-reckoning trajectory reconstructing vessel location during blackout, intersecting spill origin.",
    renderType: "blackout",
    whatChanged: "Disconnected track gap filled with calculated dead-reckoning path showing intent to hide illegal dumping.",
    whyItChanged: "Disabling AIS transponders (Class A AIS switch off) is a classic evasion tactic during illegal bilge dumping.",
    aiReasoning: "Extended Kalman Filter (EKF) uses entry/exit vectors, SOG decay, and hydrodynamic drag to bound dark trajectory.",
    scientificInterpretation: "Reconstructed dark track intersects RK4 origin hotspot at 02:14 UTC with 98.9% kinematic match.",
    judgeTakeaway: "Proves deliberate intent to evade surveillance by turning off AIS transponders prior to discharge.",
    metrics: [
      { label: "AIS Gap Duration", value: "4.2", unit: "hrs", trend: "up" },
      { label: "Dark Track Intersection", value: "98.9", unit: "%", trend: "up" },
      { label: "EKF Position Error", value: "85", unit: "m", trend: "down" },
      { label: "Evasion Intent Index", value: "CRITICAL", subtext: "Class A AIS Disable" },
    ],
    annotations: [
      {
        id: "a11-1",
        type: "callout",
        x: 48,
        y: 52,
        label: "AIS Transponder Disabled (02:00 - 06:12 UTC)",
        detail: "Illegal blackout window",
        color: "red",
      },
      {
        id: "a11-2",
        type: "arrow",
        x: 35,
        y: 65,
        label: "Reconstructed Dark Trajectory",
        detail: "Passes through spill origin",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.8942° N",
      lon: "72.7915° E",
      vvDb: -15.4,
      vhDb: -22.1,
      textureEntropy: 0.35,
      confidence: 98.9,
      classification: "Reconstructed Dark Track",
      backscatterSigma0: 0.0288,
    },
  },
  {
    id: "comp-12",
    stageNumber: 12,
    title: "SPEED PROFILE ANALYSIS",
    subtitle: "AI kinematic anomaly detector identifying deliberate slow-steaming maneuver required for slop discharge.",
    category: "Telemetry",
    confidence: 93.5,
    timestampUtc: "2026-09-12 04:18:45 UTC",
    satelliteSensor: "Vessel Telemetry SOG Time-Series",
    resolution: "1-min Time-Series",
    areaKm2: 14.2,
    gpuProcessingMs: 14,
    beforeLabel: "Raw Speed-Over-Ground Graph",
    afterLabel: "AI Slowdown Anomaly Highlight",
    beforeDescription: "Standard vessel speed graph over time without automated anomaly classification.",
    afterDescription: "Highlighted slowdown window showing speed drop from 14.2 knots cruise speed to 3.1 knots during discharge.",
    renderType: "speed_profile",
    whatChanged: "Unfiltered speed chart enhanced with highlighted anomaly window marking the exact discharge maneuver duration.",
    whyItChanged: "Vessels must slow down to 3-4 knots during bilge or slop tank washing to achieve effective pump discharge pressure.",
    aiReasoning: "Isolation Forest time-series model detects -11.1 knot speed drop anomaly lasting 28 minutes at 02:14 UTC.",
    scientificInterpretation: "SOG deceleration profile matches MARPOL Annex I illegal tank washing discharge operational signature.",
    judgeTakeaway: "Corroborates the AIS blackout with behavioral proof of vessel slowing down specifically to dump oil.",
    metrics: [
      { label: "Cruise Speed", value: "14.2", unit: "kts", trend: "neutral" },
      { label: "Discharge Speed", value: "3.1", unit: "kts", trend: "down" },
      { label: "Slowing Duration", value: "28", unit: "mins", trend: "neutral" },
      { label: "Anomaly Z-Score", value: "-4.2", unit: "sigma", trend: "down" },
    ],
    annotations: [
      {
        id: "a12-1",
        type: "callout",
        x: 50,
        y: 60,
        label: "Illegal Discharge Window (3.1 kts)",
        detail: "28-min slowdown at 02:14 UTC",
        color: "amber",
      },
    ],
    basePixel: {
      lat: "18.8942° N",
      lon: "72.7915° E",
      vvDb: -14.1,
      vhDb: -20.5,
      textureEntropy: 0.28,
      confidence: 93.5,
      classification: "SOG Telemetry Anomaly",
      backscatterSigma0: 0.0389,
    },
  },
  {
    id: "comp-13",
    stageNumber: 13,
    title: "EXPECTED HEADING VS ACTUAL HEADING",
    subtitle: "Navigation trajectory deviation analysis isolating 42° unscheduled zig-zag turn maneuver over spill locus.",
    category: "Telemetry",
    confidence: 95.0,
    timestampUtc: "2026-09-12 04:19:30 UTC",
    satelliteSensor: "COI Shipping Lane Waypoint Vector",
    resolution: "Vector Heading",
    areaKm2: 14.2,
    gpuProcessingMs: 16,
    beforeLabel: "Standard Commercial Lane Course",
    afterLabel: "Actual Track Deviation & Compass Anomaly",
    beforeDescription: "Expected direct transit heading along international commercial shipping fairway 240°.",
    afterDescription: "Actual vessel course showing 42° sharp heading deviation, loop maneuver, and compass heading change.",
    renderType: "heading",
    whatChanged: "Straight course corridor overlaid with actual zig-zag loop maneuver right over the spill convergence zone.",
    whyItChanged: "Captains alter course away from main traffic lanes to dump oil unnoticed before re-joining commercial shipping lanes.",
    aiReasoning: "Heading deviation index exceeds 3.8 standard deviations relative to commercial vessel traffic baselines.",
    scientificInterpretation: "Actual heading shifted from 240° to 198° for 32 minutes before returning to transit course.",
    judgeTakeaway: "Demonstrates intentional course deviation out of commercial channels to execute illegal dumping.",
    metrics: [
      { label: "Course Deviation", value: "42.0", unit: "deg", trend: "up" },
      { label: "Expected Heading", value: "240", unit: "deg", trend: "neutral" },
      { label: "Actual Heading", value: "198", unit: "deg", trend: "down" },
      { label: "Maneuver Duration", value: "32", unit: "mins", trend: "neutral" },
    ],
    annotations: [
      {
        id: "a13-1",
        type: "callout",
        x: 48,
        y: 45,
        label: "42° Unscheduled Course Deviation",
        detail: "Zig-zag loop over spill epicenter",
        color: "amber",
      },
    ],
    basePixel: {
      lat: "18.8942° N",
      lon: "72.7915° E",
      vvDb: -15.8,
      vhDb: -23.0,
      textureEntropy: 0.31,
      confidence: 95.0,
      classification: "Heading Anomaly Point",
      backscatterSigma0: 0.0263,
    },
  },
  {
    id: "comp-14",
    stageNumber: 14,
    title: "CURRENT MAP VS DRIFT MAP",
    subtitle: "Advection-Diffusion physics solver visualizing particle dispersion tensors and turbulent surface mixing.",
    category: "Physics",
    confidence: 97.8,
    timestampUtc: "2026-09-12 04:20:10 UTC",
    satelliteSensor: "INCOIS Ocean Hydrodynamics Engine",
    resolution: "High-Res Mesh",
    areaKm2: 14.2,
    gpuProcessingMs: 48,
    beforeLabel: "Raw INCOIS Current Vector Streamlines",
    afterLabel: "Hydrodynamic Advection-Diffusion Tensor",
    beforeDescription: "Standard 2D ocean velocity streamlines without particle diffusion or oil weathering physics.",
    afterDescription: "Particle advection-diffusion field displaying turbulent diffusion tensors (Kx, Ky) and oil slick elongation.",
    renderType: "current_drift",
    whatChanged: "Static vector arrows converted into an active fluid dynamics simulation mapping slick deformation over time.",
    whyItChanged: "Oil slicks deform non-uniformly under horizontal shear turbulence and sea surface wave dispersion.",
    aiReasoning: "Fokker-Planck diffusion solver models spatial spreading with horizontal diffusivity Kx = 10 m²/s.",
    scientificInterpretation: "Slick elongation axis aligns perfectly with principal eigenvector of surface current shear tensor.",
    judgeTakeaway: "Explains why the oil slick took its exact observed shape based on proven fluid mechanics equations.",
    metrics: [
      { label: "Diffusivity Kx", value: "10.0", unit: "m²/s", trend: "neutral" },
      { label: "Sheer Tensor Max", value: "0.042", unit: "s⁻¹", trend: "up" },
      { label: "Elongation Axis", value: "062", unit: "deg", trend: "neutral" },
      { label: "Fluid Solver Step", value: "RK4", subtext: "Advection-Diffusion" },
    ],
    annotations: [
      {
        id: "a14-1",
        type: "callout",
        x: 55,
        y: 42,
        label: "Turbulent Diffusion Elongation Axis",
        detail: "Shear tensor Kx = 10.0 m²/s",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -21.4,
      vhDb: -29.2,
      textureEntropy: 0.14,
      confidence: 97.8,
      classification: "Hydrodynamic Vector Mesh",
      backscatterSigma0: 0.0072,
    },
  },
  {
    id: "comp-15",
    stageNumber: 15,
    title: "AI CONFIDENCE BUILD",
    subtitle: "Step-by-step Bayesian feature accumulation graph illustrating how multi-source evidence reaches 94.8% certainty.",
    category: "Telemetry",
    confidence: 94.8,
    timestampUtc: "2026-09-12 04:21:00 UTC",
    satelliteSensor: "SAGAR-DRISHTI Multi-Factor Engine",
    resolution: "Fusion Pipeline",
    areaKm2: 14.2,
    gpuProcessingMs: 12,
    beforeLabel: "Zero-Prior State (0.0% Certainty)",
    afterLabel: "Multi-Source Bayesian Fusion (94.8%)",
    beforeDescription: "Initial uncalibrated observation prior before fusing multi-spectral and AIS telemetry features.",
    afterDescription: "Animated feature accumulation meter filling from 0% to 94.8% through sequential evidence integration.",
    renderType: "confidence_build",
    whatChanged: "Displays how individual probabilistic signals combine step-by-step to build unshakeable legal confidence.",
    whyItChanged: "Single-source evidence is weak, but multi-factor Bayesian update fuses radar, physics, and AIS into certainty.",
    aiReasoning: "Feature breakdown: SAR Texture (+28%), Dual-Pol (+22%), RK4 Drift (+24%), AIS Blackout (+15%), Speed Drop (+6%).",
    scientificInterpretation: "Posterior probability exceeds 94.8%, meeting Indian Evidence Act standards for legal prosecution.",
    judgeTakeaway: "Judges can see exactly how every piece of evidence contributes to the final verdict without black-box opacity.",
    metrics: [
      { label: "SAR Texture", value: "+28", unit: "%", trend: "up" },
      { label: "Dual-Pol Ratio", value: "+22", unit: "%", trend: "up" },
      { label: "RK4 Origin Match", value: "+24", unit: "%", trend: "up" },
      { label: "AIS Blackout/Speed", value: "+21", unit: "%", trend: "up" },
    ],
    annotations: [
      {
        id: "a15-1",
        type: "callout",
        x: 50,
        y: 40,
        label: "Final Fused Confidence: 94.8%",
        detail: "Court-admissible Bayesian threshold reached",
        color: "green",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -24.8,
      vhDb: -31.2,
      textureEntropy: 0.12,
      confidence: 94.8,
      classification: "Bayesian Fused State",
      backscatterSigma0: 0.0033,
    },
  },
  {
    id: "comp-16",
    stageNumber: 16,
    title: "PLAIN MAP VS INTELLIGENCE MAP",
    subtitle: "Transforming standard satellite imagery into a rich Common Operating Picture (COP) with live telemetry HUD.",
    category: "COP",
    confidence: 99.9,
    timestampUtc: "2026-09-12 04:22:00 UTC",
    satelliteSensor: "SAGAR-DRISHTI Tactical COP Engine",
    resolution: "Multi-Layer Vector",
    areaKm2: 14.2,
    gpuProcessingMs: 20,
    beforeLabel: "Plain Basemap Satellite Image",
    afterLabel: "Tactical Common Operating Picture (COP)",
    beforeDescription: "Raw satellite background without operational boundaries, shipping lanes, or vessel overlay layers.",
    afterDescription: "Multi-layer COP featuring EEZ boundary, INCOIS currents, shipping corridors, AIS targets, and live HUD.",
    renderType: "intelligence_map",
    whatChanged: "Basic map backdrop enhanced with full maritime domain awareness layers and tactical overlays.",
    whyItChanged: "Coast Guard commanders require contextual geospatial intelligence to initiate interception missions.",
    aiReasoning: "Real-time GIS compositor merges 8 active layers (EEZ, AIS, Oil, Drift, Currents, Ports, Weather, SAR).",
    scientificInterpretation: "Integrates spatial vectors, satellite rasters, and vessel kinematics into a single operational interface.",
    judgeTakeaway: "Shows how SAGAR-DRISHTI provides actionable command decision support to the Indian Coast Guard.",
    metrics: [
      { label: "Active GIS Layers", value: "8", unit: "layers", trend: "up" },
      { label: "EEZ Jurisdiction", value: "Mumbai Sector", subtext: "200 nmi limit" },
      { label: "Telemetry Refresh", value: "1.0", unit: "sec", trend: "neutral" },
      { label: "COP Status", value: "ACTIVE", subtext: "Command Ready" },
    ],
    annotations: [
      {
        id: "a16-1",
        type: "callout",
        x: 25,
        y: 25,
        label: "200 nmi Indian EEZ Jurisdiction Line",
        detail: "Legal Coast Guard enforcement zone",
        color: "teal",
      },
      {
        id: "a16-2",
        type: "arrow",
        x: 65,
        y: 50,
        label: "Active Oil Contamination COP Layer",
        detail: "Integrated satellite & AIS view",
        color: "amber",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -22.0,
      vhDb: -29.0,
      textureEntropy: 0.16,
      confidence: 99.9,
      classification: "Tactical COP Synthesis",
      backscatterSigma0: 0.0063,
    },
  },
  {
    id: "comp-17",
    stageNumber: 17,
    title: "PREDICTION VS VERIFIED EVIDENCE",
    subtitle: "Immutably sealing AI model predictions into SHA-256 Merkle tree blocks with digital cryptographic signatures.",
    category: "Evidence",
    confidence: 100.0,
    timestampUtc: "2026-09-12 04:23:00 UTC",
    satelliteSensor: "SHA-256 Merkle Ledger Node #01",
    resolution: "256-bit Cryptographic",
    areaKm2: 14.2,
    gpuProcessingMs: 8,
    beforeLabel: "Unsigned Model Output",
    afterLabel: "SHA-256 Immutable Merkle Block",
    beforeDescription: "Raw AI predictions susceptible to legal challenges regarding data tampering or post-hoc alteration.",
    afterDescription: "Cryptographically hashed Merkle block sealed with Ed25519 digital signature by Indian Coast Guard Authority.",
    renderType: "evidence_proof",
    whatChanged: "Volatile prediction data locked into a permanent cryptographic evidence chain with verified SHA-256 hashes.",
    whyItChanged: "Court admissibility under Section 65B of Indian Evidence Act requires cryptographic proof of chain of custody.",
    aiReasoning: "Merkle tree computes parent root hash e8f4...91c2 from satellite raster, RK4 points, and AIS logs.",
    scientificInterpretation: "Ed25519 signature guarantees zero data alteration between satellite acquisition and court filing.",
    judgeTakeaway: "Provides absolute legal certainty that evidence was sealed at the exact time of detection and never altered.",
    metrics: [
      { label: "Hash Algorithm", value: "SHA-256", subtext: "256-bit Digest" },
      { label: "Merkle Root Hash", value: "e8f4a...91c2", subtext: "Verified Valid" },
      { label: "Ed25519 Signature", value: "VALID", subtext: "ICG Command Key" },
      { label: "Tamper Risk", value: "0.000%", trend: "down" },
    ],
    annotations: [
      {
        id: "a17-1",
        type: "callout",
        x: 48,
        y: 45,
        label: "Merkle Root Sealed (e8f4a...91c2)",
        detail: "Cryptographically verified immutable block",
        color: "green",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -24.8,
      vhDb: -31.2,
      textureEntropy: 0.12,
      confidence: 100.0,
      classification: "Cryptographically Sealed Evidence",
      backscatterSigma0: 0.0033,
    },
  },
  {
    id: "comp-18",
    stageNumber: 18,
    title: "VERIFIED VS TAMPERED",
    subtitle: "Simulating adversarial data tampering attempt to demonstrate instant cryptographic detection and recovery.",
    category: "Evidence",
    confidence: 100.0,
    timestampUtc: "2026-09-12 04:24:00 UTC",
    satelliteSensor: "SHA-256 Merkle Ledger Node #01",
    resolution: "Cryptographic Guard",
    areaKm2: 14.2,
    gpuProcessingMs: 6,
    beforeLabel: "Valid Cryptographic Evidence Chain",
    afterLabel: "Tamper Detected & Auto-Recovered",
    beforeDescription: "Valid Merkle chain state with matching SHA-256 hashes and green verification indicators.",
    afterDescription: "Simulated tamper alert showing red hash mismatch, broken chain warning, and 1-click verification restore.",
    renderType: "tamper_sim",
    whatChanged: "Simulates an illegal attempt to modify vessel coordinates, showing instant detection and recovery.",
    whyItChanged: "Even a single modified bit in telemetry breaks the SHA-256 hash avalanche, triggering an instant alarm.",
    aiReasoning: "Merkle root mismatch (expected e8f4... vs computed a1d9...) immediately invalidates corrupted node.",
    scientificInterpretation: "Cryptographic hash avalanche effect changes ~50% of digest bits for 1-bit payload modification.",
    judgeTakeaway: "Proves SAGAR-DRISHTI is tamper-proof against internal corruption or external cyber tampering.",
    metrics: [
      { label: "Tamper Detection", value: "INSTANT", subtext: "< 1 ms response" },
      { label: "Hash Avalanche Delta", value: "51.2", unit: "%", trend: "up" },
      { label: "Chain Status", value: "PROTECTED", subtext: "Auto-Recoverable" },
      { label: "Sec 65B Compliance", value: "PASSED", subtext: "Indian Evidence Act" },
    ],
    annotations: [
      {
        id: "a18-1",
        type: "callout",
        x: 50,
        y: 42,
        label: "HASH MISMATCH DETECTED (a1d9... ≠ e8f4...)",
        detail: "1-bit coordinate modification attempt blocked",
        color: "red",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -24.8,
      vhDb: -31.2,
      textureEntropy: 0.12,
      confidence: 100.0,
      classification: "Tamper Detection Shield",
      backscatterSigma0: 0.0033,
    },
  },
  {
    id: "comp-19",
    stageNumber: 19,
    title: "MISSION TIMELINE BUILD",
    subtitle: "Synchronized 7-stage end-to-end investigation progression linking initial detection to legal dossier generation.",
    category: "Telemetry",
    confidence: 99.5,
    timestampUtc: "2026-09-12 04:25:00 UTC",
    satelliteSensor: "SAGAR-DRISHTI Master Choreographer",
    resolution: "Stage Sequence",
    areaKm2: 14.2,
    gpuProcessingMs: 10,
    beforeLabel: "Fragmented Detection Events",
    afterLabel: "Synchronized 7-Stage Investigation Workflow",
    beforeDescription: "Isolated detection logs and disconnected analytical outputs.",
    afterDescription: "Seamless 7-stage chronological investigation trajectory from Sentinel-1 overpass to legal dossier.",
    renderType: "timeline_build",
    whatChanged: "Connects all individual analytical components into a unified, reproducible investigation workflow.",
    whyItChanged: "Judges need to follow the complete logical arc from initial satellite detection to vessel attribution.",
    aiReasoning: "State machine tracks transition events across Detection → Drift → AIS → Attribution → Evidence → Dossier.",
    scientificInterpretation: "Complete end-to-end processing completed in 49 seconds of automated pipeline execution.",
    judgeTakeaway: "Demonstrates an end-to-end automated platform that handles everything from satellite pass to court evidence.",
    metrics: [
      { label: "Total Pipeline Stages", value: "7", unit: "stages", trend: "neutral" },
      { label: "End-to-End Latency", value: "49.2", unit: "sec", trend: "down" },
      { label: "Automation Index", value: "100.0", unit: "%", trend: "up" },
      { label: "Workflow Status", value: "COMPLETE", subtext: "Dossier Ready" },
    ],
    annotations: [
      {
        id: "a19-1",
        type: "callout",
        x: 50,
        y: 45,
        label: "7-Stage Mission Replay Active",
        detail: "Synchronized cross-module workflow",
        color: "teal",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -22.4,
      vhDb: -29.1,
      textureEntropy: 0.14,
      confidence: 99.5,
      classification: "Mission Master State",
      backscatterSigma0: 0.0058,
    },
  },
  {
    id: "comp-20",
    stageNumber: 20,
    title: "RAW INCIDENT → FINAL DOSSIER",
    subtitle: "Complete transformation from raw satellite imagery to a court-admissible UNCLOS & MARPOL intelligence dossier.",
    category: "Legal Dossier",
    confidence: 94.8,
    timestampUtc: "2026-09-12 04:26:00 UTC",
    satelliteSensor: "SAGAR-DRISHTI Legal Engine",
    resolution: "Court-Admissible Dossier",
    areaKm2: 14.2,
    gpuProcessingMs: 150,
    beforeLabel: "Unprocessed Raw Satellite Input",
    afterLabel: "Court-Admissible Legal Dossier Report",
    beforeDescription: "Raw satellite radar raster input without vessel identification, drift proof, or legal attribution.",
    afterDescription: "Compiled Legal Dossier featuring vessel master details, RK4 origin proof, SHA-256 hashes, and \$1.42M penalty assessment.",
    renderType: "final_dossier",
    whatChanged: "Raw pixels transformed into an executive legal dossier ready for international maritime court submission.",
    whyItChanged: "Prosecuting illegal marine pollution under UNCLOS Art. 221 requires combining satellite, hydrodynamic, and AIS evidence.",
    aiReasoning: "Legal Engine compiles all 19 preceding analysis steps into a structured, cryptographically signed PDF dossier.",
    scientificInterpretation: "Assesses $1.42M financial liability under MARPOL Annex I based on 142 m³ heavy crude spill volume.",
    judgeTakeaway: "SAGAR-DRISHTI doesn't just detect spills — it delivers complete, legally actionable cases ready for enforcement.",
    metrics: [
      { label: "Financial Liability", value: "$1.42M", subtext: "MARPOL Annex I Fine" },
      { label: "Legal Readiness", value: "COURT READY", subtext: "UNCLOS Art. 221" },
      { label: "Culprit IMO", value: "9123456", subtext: "MV OCEAN CROWN" },
      { label: "Evidentiary Rating", value: "A1 EXCELLENT", trend: "up" },
    ],
    annotations: [
      {
        id: "a20-1",
        type: "callout",
        x: 50,
        y: 40,
        label: "FINAL LEGAL DOSSIER (SD-2026-00421)",
        detail: "Court-admissible UNCLOS / MARPOL prosecution case",
        color: "green",
      },
    ],
    basePixel: {
      lat: "18.9214° N",
      lon: "72.8341° E",
      vvDb: -24.8,
      vhDb: -31.2,
      textureEntropy: 0.12,
      confidence: 94.8,
      classification: "Court-Ready Legal Dossier",
      backscatterSigma0: 0.0033,
    },
  },
];
